AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Parameters:
  HelloWorldFunctionName:
    Default: HelloWorld
    Type: String
    Description: HelloWorld lambda default name

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Handler: index.handler

Resources:
  # TestLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     CompatibleRuntimes: [nodejs20.x]
  #     ContentUri: layers/test_layer
  #     Description: Test Layer
  #     LayerName: test-layer
  #     RetentionPolicy: Delete
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/hello-world/
      FunctionName: !Ref HelloWorldFunctionName
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      # BuildProperties:
      #   Minify: false
      #   Target: "es2015"
      #   Sourcemap: true
      #   EntryPoints: 
      #     - index.ts
      #   External:
      #     - "<package-to-exclude>"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
