version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g esbuild
      - npm install 
  pre_build:
    commands:
      - echo 'pre-build commands are empty'
  build:
    commands:
      - sam build
  post_build:
    commands:
      - ./ci/set_envs.sh
      - sam deploy $parameter_overrides --stack-name=sam-app-$ENV --config-file ./ci/samconfig.toml --region=us-east-1