version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install 
  pre_build:
    commands:
      - echo 'pre-build commands are empty'
  build:
    commands:
      - sam build
  post_build:
    commands:
      - ./ci/deploy.sh