version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - npx tsc
  build:
    commands:
      - sam build
  post_build:
    commands:
      - ./ci/deploy.sh